apiVersion: v1
kind: Service
metadata:
  name: helloworldapi-load-balancer-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
spec:
  selector:
    app: helloworldapi
  ports:
    - port: 8080
      targetPort: 5000
  type: LoadBalancer